{
  imports = [
    ./modules/nvim-autopairs.nix
    ./modules/nvim-surround.nix
    ./modules/colorizer.nix
    ./modules/barbar.nix
    ./modules/comment.nix
    ./modules/floaterm.nix
    ./modules/gruvbox.nix
    ./modules/lualine.nix
    ./modules/lsp.nix
    ./modules/neo-tree.nix
    ./modules/neoscroll.nix
    ./modules/snacks.nix
    ./modules/startify.nix
    ./modules/telescope.nix
    ./modules/vimtex.nix
    ./modules/transparent.nix
    ./modules/treesitter.nix
    ./modules/web-devicons.nix
  ];
}
