# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5a10d72b-5ec6-4b1d-9fd8-17c84e5f4b8e";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/ad60d70a-147b-4f77-84f0-daad5f89206b";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5a10d72b-5ec6-4b1d-9fd8-17c84e5f4b8e";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/5a10d72b-5ec6-4b1d-9fd8-17c84e5f4b8e";
      fsType = "btrfs";
      options = [ "subvol=@var_log" "compress=zstd" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/5a10d72b-5ec6-4b1d-9fd8-17c84e5f4b8e";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/9631-04B0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
